/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as ColumnsRouteImport } from './routes/columns'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ExploreCrosstabRouteImport } from './routes/explore/crosstab'
import { Route as ApiSchemaRouteImport } from './routes/api/schema'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiCrosstabRouteImport } from './routes/api/crosstab'
import { Route as ApiStatsColumnRouteImport } from './routes/api/stats.$column'

const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnsRoute = ColumnsRouteImport.update({
  id: '/columns',
  path: '/columns',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCrosstabRoute = ExploreCrosstabRouteImport.update({
  id: '/explore/crosstab',
  path: '/explore/crosstab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaRoute = ApiSchemaRouteImport.update({
  id: '/api/schema',
  path: '/api/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrosstabRoute = ApiCrosstabRouteImport.update({
  id: '/api/crosstab',
  path: '/api/crosstab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsColumnRoute = ApiStatsColumnRouteImport.update({
  id: '/api/stats/$column',
  path: '/api/stats/$column',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/columns': typeof ColumnsRoute
  '/data-quality': typeof DataQualityRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/notebook': typeof NotebookRoute
  '/profile': typeof ProfileRoute
  '/relationships': typeof RelationshipsRoute
  '/sql': typeof SqlRoute
  '/api/crosstab': typeof ApiCrosstabRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRoute
  '/explore/crosstab': typeof ExploreCrosstabRoute
  '/explore/': typeof ExploreIndexRoute
  '/api/stats/$column': typeof ApiStatsColumnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/columns': typeof ColumnsRoute
  '/data-quality': typeof DataQualityRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/notebook': typeof NotebookRoute
  '/profile': typeof ProfileRoute
  '/relationships': typeof RelationshipsRoute
  '/sql': typeof SqlRoute
  '/api/crosstab': typeof ApiCrosstabRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRoute
  '/explore/crosstab': typeof ExploreCrosstabRoute
  '/explore': typeof ExploreIndexRoute
  '/api/stats/$column': typeof ApiStatsColumnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/columns': typeof ColumnsRoute
  '/data-quality': typeof DataQualityRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/notebook': typeof NotebookRoute
  '/profile': typeof ProfileRoute
  '/relationships': typeof RelationshipsRoute
  '/sql': typeof SqlRoute
  '/api/crosstab': typeof ApiCrosstabRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRoute
  '/explore/crosstab': typeof ExploreCrosstabRoute
  '/explore/': typeof ExploreIndexRoute
  '/api/stats/$column': typeof ApiStatsColumnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/columns'
    | '/data-quality'
    | '/llms.txt'
    | '/notebook'
    | '/profile'
    | '/relationships'
    | '/sql'
    | '/api/crosstab'
    | '/api/feedback'
    | '/api/health'
    | '/api/query'
    | '/api/schema'
    | '/explore/crosstab'
    | '/explore/'
    | '/api/stats/$column'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/columns'
    | '/data-quality'
    | '/llms.txt'
    | '/notebook'
    | '/profile'
    | '/relationships'
    | '/sql'
    | '/api/crosstab'
    | '/api/feedback'
    | '/api/health'
    | '/api/query'
    | '/api/schema'
    | '/explore/crosstab'
    | '/explore'
    | '/api/stats/$column'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/columns'
    | '/data-quality'
    | '/llms.txt'
    | '/notebook'
    | '/profile'
    | '/relationships'
    | '/sql'
    | '/api/crosstab'
    | '/api/feedback'
    | '/api/health'
    | '/api/query'
    | '/api/schema'
    | '/explore/crosstab'
    | '/explore/'
    | '/api/stats/$column'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ColumnsRoute: typeof ColumnsRoute
  DataQualityRoute: typeof DataQualityRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NotebookRoute: typeof NotebookRoute
  ProfileRoute: typeof ProfileRoute
  RelationshipsRoute: typeof RelationshipsRoute
  SqlRoute: typeof SqlRoute
  ApiCrosstabRoute: typeof ApiCrosstabRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiSchemaRoute: typeof ApiSchemaRoute
  ExploreCrosstabRoute: typeof ExploreCrosstabRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ApiStatsColumnRoute: typeof ApiStatsColumnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columns': {
      id: '/columns'
      path: '/columns'
      fullPath: '/columns'
      preLoaderRoute: typeof ColumnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/crosstab': {
      id: '/explore/crosstab'
      path: '/explore/crosstab'
      fullPath: '/explore/crosstab'
      preLoaderRoute: typeof ExploreCrosstabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema': {
      id: '/api/schema'
      path: '/api/schema'
      fullPath: '/api/schema'
      preLoaderRoute: typeof ApiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crosstab': {
      id: '/api/crosstab'
      path: '/api/crosstab'
      fullPath: '/api/crosstab'
      preLoaderRoute: typeof ApiCrosstabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/$column': {
      id: '/api/stats/$column'
      path: '/api/stats/$column'
      fullPath: '/api/stats/$column'
      preLoaderRoute: typeof ApiStatsColumnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ColumnsRoute: ColumnsRoute,
  DataQualityRoute: DataQualityRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NotebookRoute: NotebookRoute,
  ProfileRoute: ProfileRoute,
  RelationshipsRoute: RelationshipsRoute,
  SqlRoute: SqlRoute,
  ApiCrosstabRoute: ApiCrosstabRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiSchemaRoute: ApiSchemaRoute,
  ExploreCrosstabRoute: ExploreCrosstabRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ApiStatsColumnRoute: ApiStatsColumnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
