/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSchemaRouteImport } from './routes/api/schema'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCrosstabRouteImport } from './routes/api/crosstab'
import { Route as ApiStatsColumnRouteImport } from './routes/api/stats.$column'

const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaRoute = ApiSchemaRouteImport.update({
  id: '/api/schema',
  path: '/api/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrosstabRoute = ApiCrosstabRouteImport.update({
  id: '/api/crosstab',
  path: '/api/crosstab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsColumnRoute = ApiStatsColumnRouteImport.update({
  id: '/api/stats/$column',
  path: '/api/stats/$column',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/sql': typeof SqlRoute
  '/api/crosstab': typeof ApiCrosstabRoute
  '/api/health': typeof ApiHealthRoute
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRoute
  '/api/stats/$column': typeof ApiStatsColumnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/sql': typeof SqlRoute
  '/api/crosstab': typeof ApiCrosstabRoute
  '/api/health': typeof ApiHealthRoute
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRoute
  '/api/stats/$column': typeof ApiStatsColumnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/sql': typeof SqlRoute
  '/api/crosstab': typeof ApiCrosstabRoute
  '/api/health': typeof ApiHealthRoute
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRoute
  '/api/stats/$column': typeof ApiStatsColumnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/profile'
    | '/sql'
    | '/api/crosstab'
    | '/api/health'
    | '/api/query'
    | '/api/schema'
    | '/api/stats/$column'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/profile'
    | '/sql'
    | '/api/crosstab'
    | '/api/health'
    | '/api/query'
    | '/api/schema'
    | '/api/stats/$column'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/profile'
    | '/sql'
    | '/api/crosstab'
    | '/api/health'
    | '/api/query'
    | '/api/schema'
    | '/api/stats/$column'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ProfileRoute: typeof ProfileRoute
  SqlRoute: typeof SqlRoute
  ApiCrosstabRoute: typeof ApiCrosstabRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiSchemaRoute: typeof ApiSchemaRoute
  ApiStatsColumnRoute: typeof ApiStatsColumnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema': {
      id: '/api/schema'
      path: '/api/schema'
      fullPath: '/api/schema'
      preLoaderRoute: typeof ApiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crosstab': {
      id: '/api/crosstab'
      path: '/api/crosstab'
      fullPath: '/api/crosstab'
      preLoaderRoute: typeof ApiCrosstabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/$column': {
      id: '/api/stats/$column'
      path: '/api/stats/$column'
      fullPath: '/api/stats/$column'
      preLoaderRoute: typeof ApiStatsColumnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ProfileRoute: ProfileRoute,
  SqlRoute: SqlRoute,
  ApiCrosstabRoute: ApiCrosstabRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiSchemaRoute: ApiSchemaRoute,
  ApiStatsColumnRoute: ApiStatsColumnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
